fix: missing staticfiles manifest entry error
Use Django collectstatic to include frontend assets for production instead of
just copying them as 1) that doesn't work and results in the missing manifest
error & 2) we wouldn't get cache busting support.

An example of the full error is:

  ValueError: Missing staticfiles manifest entry for 'assets/styles-CYPD3OLl.css'