Fix tests broken in previous commit
The commit that broke the tests was 6fd85d053eccd46450f51a17cad984bfb8e4b763
and the error when running tests is:

  django.core.files.storage.handler.InvalidStorageError: Could not find config for 'file_upload' in settings.STORAGES.

We simply have to supply a reasonable storage setting for file uploads when
testing which is to just use file system storage.