Use uv for dependency management & update all packages to the latest possible
Because we want to get the security updates & other features available in later
package versions.

A whole bunch of changes were required for this beyond just setting up uv as
the dependency manager. The notable changes were:

- Update to django version 5.1.1 from 4.0.10 and address deprecations

  Also had to change the django-q dependency to django-q2 as development of
  django-q has stalled and it has not be updated to support django version > 5.
  Without this change we get the following error that ultimately originates
  from django-q:

    ImportError: cannot import name 'baseconv' from 'django.utils'

  as the baseconv module has been deprecated in django 5. See
  https://code.djangoproject.com/ticket/32712

  The django-q2 package is a drop-in replacement for django-q with ongoing
  development.

- Update wagtail to version 6.2.1 from 2.16.1

  Many changes & adjustments to the wagtail data models were required for this
  change.

- Update file & static file config due to deprecation

  The STATICFILES_STORAGE & DEFAULT_FILE_STORAGE config options are deprecated.
  See https://docs.djangoproject.com/en/5.1/releases/4.2/#custom-file-storages

- Change CheckConstraint named parameter due to deprecation