Prevent occasional DataError when running tests
The full error is

  django.db.utils.DataError: value too long for type character varying(64)

Occasionally the faker sentence provider generates text with more than 64
characters which is that maximum length of the Task name field. You cannot
specify a maximum length with faker so we try for text around but not over the
max length.